language: node_js
cache: yarn
node_js:
  - node
  - '10'
  - '8'
os:
  - linux
  - osx
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
script:
  - npm test
after_success:
  - npm run coverage
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npm run build
        - npx semantic-release
      env:
        - secure: q/PCJJu3iAj/Vwdi1uoecOf4AugcR+IBmTwKRigUhj3hn/p/l8iYCkQ0eYM/q7mC6W8y/huxX4qqbOmQx0ys/ECJ8uSzjzmqEMxhIhinILE3/nxbIADzbMZIaZ9xK/vK/B8hIaDeR2YWoot2I9bqO5sVEmqc571odnBxvnTsi36/QpsKUlAy+LsNYFj8kWaU1BF66356wXynTqso6qqVfu+U17Gaj6fovCr/CdIpwhypzIxOJyEFoT7adylxSw2fehUnua8RVlOsqCBSdqDPP9Zz2/8kRAC2xJNtJUBfe6dQ675ue33ciYisCpZC+Hpoq/lgJVUffSiJCBGnr1upv97wafG3NTFDxoLZKkxe4Yxzk0HjMSQZ7BE7RQW6euwbER+AGWQwxKL7k10fV5mgI4UZVqBYzy+4GcNhCMExwM1UzvzqJreDHxeNEd7WHi6vgbMsxXU11vfxDrjR0eMGACFD2XY3nSqXUBAP3nTJrB4VtZryXSA/wQ2tZ6qu7QsFOZmTiIENoymj74EDRi/q32xTNwDRx0JsgoBJ0fVwh3qsA0JWwqwdVKcMvvFpS3YP0NgL1zC3SNnHS4Mxx6pLJmWnTWXJIvluGB5IJkjieSc65/nzLKo/I7a/QW5cA8e4qWw2edY3+4DbvciKNeRp5h1hk6f1i33I5/NolCyAKks=
